export const PAYMENT_STEP = {
    CREATE_CUSTOMER: "CREATE_CUSTOMER",
    CREATE_VIRTUAL_ACCOUNT: "CREATE_VIRTUAL_ACCOUNT",
    SEND_MESSAGE: "SEND_MESSAGE",
    OATH_TOKEN_REQUEST: "OATH_TOKEN_REQUEST"
}